### PR TITLE
Improve the UI, add stylings

### LINKED ISSUE #1: refactor
- [ ] remove hr, br, change class name with meaningful name. because I'm frontend dev.
- [ ] make this repo beautiful & this projects looks so serious
- [ ] improve ui

### PR DESCRIPTION
**Pull request by afifsohaili**
Fixes #1.

### CODE REVIEW

**Comment by filosofikode** [comment]
great! Big thanks @afifsohaili. Let me check it

**Comment by afifsohaili** [comment]
Hey. I could make some changes tomorrow morning. Forgot to check the mobile view lol

**Comment by filosofikode** [comment]
yeah, no problem. keep your great work!

**Comment by afifsohaili** [comment]
Hey, I made some changes. Let me know if there's any more comments.

**Comment by filosofikode** [comment]
Great, your pull request lives here: https://evilnews-xvfusoahoi.now.sh. I will merge it in afternoon UTC +7

**Pull request merged**
